### ISSUE TITLE
path problem

### ISSUE THREAD

**Issue by Madmin27** [hiephtdev/huong-dan-chay-full-node-avail#1]
Hello. I installed Linux 22.04 under WSL and used your commands. He made no mistakes.
However, when I queried with the "systemctl status availd.service" command, I received the following error and the node is not working. Do you have any suggestions?

I am running Avail Node on Ubuntu 20.04 on the same PC. I wanted to try your commands on 22.04.

`○ availd.service - Avail Validator
     Loaded: bad-setting (Reason: Unit availd.service has a bad unit file setting.)
     Active: inactive (dead)

Nov 08 22:59:00 DESKTOP-SP74792 systemd[1]: /etc/systemd/system/availd.service:8: Neither a valid executable name nor an absolute path: $HOME/avail-node/avail/target/release/data-avail
Nov 08 22:59:00 DESKTOP-SP74792 systemd[1]: availd.service: Unit configuration has fatal error, unit will not be started.
Nov 08 23:01:03 DESKTOP-SP74792 systemd[1]: /etc/systemd/system/availd.service:8: Neither a valid executable name nor an absolute path: $HOME/avail-node/avail/target/release/data-avail
Nov 08 23:01:03 DESKTOP-SP74792 systemd[1]: availd.service: Unit configuration has fatal error, unit will not be started.`

**Comment by 0xsyncroot** [comment]
I have updated the bug fix version, please review the latest version, thank you.

**Comment by 0xsyncroot** [comment]
![Screenshot 2023-11-09 083359](https://github.com/hiephtdev/huong-dan-chay-full-node-avail/assets/100410288/6e2c2953-d5b2-4031-b81d-99a45bc64dc5)
