### ISSUE TITLE
--chain  problem?

### ISSUE THREAD

**Issue by Madmin27** [hiephtdev/huong-dan-chay-full-node-avail#2]
Hello
I installed it as you wrote, this time the home problem occurred again, but I fixed the problem. I go into the logs and watch them instantly and avail-node is working.
But there is no one working under my name on the Telemetry page?
I have a node installed on Ubuntu 20.04 on other servers and in the same pc wsl.

--chain goldberg could it be a problem? On the avail project githup page "https://github.com/availproject/avail", the code cargo run --locked --release -- --chain kate -d ./output has been run.

Could you have missed this? If I need to make Kate, can you clean the old one and write how to do it?

I am thankful to you

**Comment by Madmin27** [comment]
Windows portlarını açmayı deneyeceğim

**Comment by 0xsyncroot** [comment]
The chain has no issues, sir. If your node is running but not showing up on the telemetry page, please check if the GoldBerg tab is correct. If it is, wait for the node to finish syncing. Once you see the import logs, your node will appear on the telemetry page. Don't worry too much about this; just ensure your node is running, and the process will be complete.

**Comment by Madmin27** [comment]
Dude, do I need to open windows ports?

**Comment by 0xsyncroot** [comment]
Are you running an Ubuntu-based system on Windows Subsystem for Linux (WSL)?

**Comment by 0xsyncroot** [comment]
If you're running it on a personal machine within a home network, you'll need to open the port from your network modem. Please provide a clear description of your case for better assistance

**Comment by 0xsyncroot** [comment]
I request permission to close this issue here. If there are any further concerns, please create a new separate issue. Thank you
