### ISSUE TITLE
not visible in telemetry

### ISSUE THREAD

**Issue by Madmin27** [hiephtdev/huong-dan-chay-full-node-avail#3]
I had previously installed it as 1.7 and it was visible and active on the Telemetry screen.
Now I wanted to install 1.8 and followed your commands. My system is 8 GB Memory / 2 AMD vCPUs / 100 GB Disk / FRA1 - Ubuntu 22.04 (LTS) x64.

When I watch with journalctl -f -u availd, I can watch as follows
![Ekran görüntüsü 2023-11-10 215626](https://github.com/hiephtdev/huong-dan-chay-full-node-avail/assets/94014225/98039c76-efdc-4971-88b9-24a87805312f)

digitalOcean firewall screen
![Ekran görüntüsü 2023-11-10 220214](https://github.com/hiephtdev/huong-dan-chay-full-node-avail/assets/94014225/aae526f4-a632-4e04-a6d2-84b3b2ffd4b8)
I would be happy if you help me solve the problem.

**Comment by Madmin27** [comment]
![Ekran görüntüsü 2023-11-10 221055](https://github.com/hiephtdev/huong-dan-chay-full-node-avail/assets/94014225/d5be01fa-23a1-4234-bcab-1aa7828d4c3d)
I saw it on the goldberg page, thank you

**Comment by Madmin27** [comment]
![Ekran görüntüsü 2023-11-10 224022](https://github.com/hiephtdev/huong-dan-chay-full-node-avail/assets/94014225/4f2411d8-397a-494f-bc26-2f0b66d4e44c)
What can I do for my high ping problem?

**Comment by 0xsyncroot** [comment]
Don't worry too much about the ping; a high ping could be due to your node being quite far from others, resulting in slightly slower synchronization between nodes. If you want to improve it, consider choosing a VPS in a different location, for instance, a VPS near Dublin
