### ISSUE TITLE
the --prometheus-external command?

### ISSUE THREAD

**Issue by Madmin27** [hiephtdev/huong-dan-chay-full-node-avail#4]
Hello
I set up avail node with your codes. It works when you remove the "--prometheus-external" keywords in availd.service, but when you add it, it doesn't work.

What is the function of the --prometheus-external command? Do you mind if I remove it?
Thanks

**Comment by 0xsyncroot** [comment]
I added this tag to supplement monitoring as instructed on the avail project doc page, and I tried running the node again, and it started normally. Can you please send me a specific error screenshot of yours? And I think removing it should be fine, I'm trying to remove it now.
![Screenshot 2023-11-21 162440](https://github.com/hiephtdev/huong-dan-chay-full-node-avail/assets/100410288/c1da9bdf-4ee5-4f8c-9aed-5ed89d5593aa)

**Comment by 0xsyncroot** [comment]
one file: curl -s https://raw.githubusercontent.com/hiephtdev/huong-dan-chay-full-node-avail/main/auto-run-avail-full-node.sh | bash

**Comment by 0xsyncroot** [comment]
I tried --prometheus-external again, and it indeed exposes Prometheus to display node information on the monitor without affecting the node.
